/* Generated by scripts/embed-table.ts, checked against https://oembed.com/providers.json.
 * Do not edit: run `pnpm embed:table`.
 *
 * The broad half of the list of places a note can show rather than link to: the
 * providers nobody has driven a frame of by hand, each one an address pattern and
 * the frame it turns into. 42 rows, of which 25 are in the public oEmbed
 * registry - which is where their hosts come from, so a provider that takes on a
 * new domain is a regeneration rather than a rewrite. The rest publish an embed
 * address and no oEmbed endpoint at all, Google Drive and Twitch and gists and
 * Typeform among them, which is why this is a table and not a filter.
 *
 * What every field means, and what is done to a capture before it reaches a
 * frame, is in providers.ts. Nothing here is a frame: a row is read only when a
 * note points at one of its hosts, and what it yields is an address. */

import type { Listed } from './providers'

export const EMBEDDABLE: readonly Listed[] = [
  {
    id: 'drive',
    name: 'Google Drive',
    mark: 'open',
    shape: 720,
    hosts: ['drive.google.com'],
    frames: [['^/file/d/([\\w-]+)', 'https://drive.google.com/file/d/$1/preview']],
  },
  {
    id: 'gdocs',
    name: 'Google Docs',
    mark: 'open',
    shape: 720,
    hosts: ['docs.google.com'],
    frames: [
      ['^/document/d/([\\w-]+)', 'https://docs.google.com/document/d/$1/preview'],
      ['^/spreadsheets/d/([\\w-]+)', 'https://docs.google.com/spreadsheets/d/$1/preview'],
      ['^/forms/d/e/([\\w-]+)', 'https://docs.google.com/forms/d/e/$1/viewform?embedded=true'],
      ['^/forms/d/([\\w-]+)', 'https://docs.google.com/forms/d/$1/viewform?embedded=true'],
    ],
  },
  {
    id: 'gslides',
    name: 'Google Slides',
    mark: 'open',
    shape: 'video',
    hosts: ['docs.google.com'],
    frames: [['^/presentation/d/([\\w-]+)', 'https://docs.google.com/presentation/d/$1/embed']],
  },
  {
    id: 'miro',
    name: 'Miro',
    mark: 'open',
    shape: 'video',
    hosts: ['miro.com'],
    frames: [['^/app/board/([\\w=-]+)', 'https://miro.com/app/live-embed/$1/']],
  },
  {
    id: 'twitch',
    name: 'Twitch',
    mark: 'play',
    shape: 'video',
    hosts: ['m.twitch.tv', 'player.twitch.tv', 'twitch.tv'],
    frames: [
      [
        '^/videos/(\\d+)',
        'https://player.twitch.tv/?video=$1&parent=localhost&parent=tauri.localhost&autoplay=false',
      ],
      [
        '^/(\\w+)/clip/([\\w-]+)',
        'https://clips.twitch.tv/embed?clip=$2&parent=localhost&parent=tauri.localhost&autoplay=false',
      ],
      [
        '^/(\\w+)$',
        'https://player.twitch.tv/?channel=$1&parent=localhost&parent=tauri.localhost&autoplay=false',
      ],
    ],
  },
  {
    id: 'twitch-clip',
    name: 'Twitch',
    mark: 'play',
    shape: 'video',
    hosts: ['clips.twitch.tv'],
    frames: [
      [
        '^/([\\w-]+)$',
        'https://clips.twitch.tv/embed?clip=$1&parent=localhost&parent=tauri.localhost&autoplay=false',
      ],
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    mark: 'play',
    shape: 740,
    hosts: ['tiktok.com'],
    frames: [
      ['^/@[\\w.-]+/video/(\\d+)', 'https://www.tiktok.com/embed/v2/$1'],
      ['^/embed/v2/(\\d+)', 'https://www.tiktok.com/embed/v2/$1'],
      ['^/v/(\\d+)', 'https://www.tiktok.com/embed/v2/$1'],
    ],
  },
  {
    id: 'gist',
    name: 'GitHub Gist',
    mark: 'open',
    shape: 400,
    hosts: ['gist.github.com'],
    frames: [['^/([\\w-]+)/([0-9a-f]{7,64})', 'https://gist.github.com/$1/$2.pibb']],
  },
  {
    id: 'typeform',
    name: 'Typeform',
    mark: 'open',
    shape: 560,
    hosts: ['form.typeform.com'],
    frames: [['^/to/([\\w-]+)', 'https://form.typeform.com/to/$1']],
  },
  {
    id: 'sketchfab',
    name: 'Sketchfab',
    mark: 'open',
    shape: 'video',
    hosts: ['sketchfab.com'],
    frames: [
      ['^/3d-models/[\\w-]*-([0-9a-f]{12,40})$', 'https://sketchfab.com/models/$1/embed'],
      ['^/models/([0-9a-f]{12,40})', 'https://sketchfab.com/models/$1/embed'],
    ],
  },
  {
    id: 'dailymotion',
    name: 'Dailymotion',
    mark: 'play',
    shape: 'video',
    hosts: ['dailymotion.com', 'geo.dailymotion.com'],
    frames: [['^/video/(\\w+)', 'https://geo.dailymotion.com/player.html?video=$1']],
  },
  {
    id: 'ted',
    name: 'TED',
    mark: 'play',
    shape: 'video',
    hosts: ['embed.ted.com', 'ted.com'],
    frames: [['^/talks/([\\w-]+)', 'https://embed.ted.com/talks/$1']],
  },
  {
    id: 'reddit',
    name: 'Reddit',
    mark: 'open',
    shape: 500,
    hosts: ['reddit.com'],
    frames: [
      ['^/r/(\\w+)/comments/(\\w+)', 'https://www.redditmedia.com/r/$1/comments/$2/?embed=true'],
    ],
  },
  {
    id: 'giphy',
    name: 'GIPHY',
    mark: 'open',
    shape: 'video',
    hosts: ['giphy.com', 'gph.is', 'media.giphy.com'],
    frames: [
      ['^/gifs/[\\w-]*-(\\w+)$', 'https://giphy.com/embed/$1'],
      ['^/gifs/(\\w+)$', 'https://giphy.com/embed/$1'],
      ['^/clips/[\\w-]*-(\\w+)$', 'https://giphy.com/embed/$1'],
      ['^/embed/(\\w+)', 'https://giphy.com/embed/$1'],
    ],
  },
  {
    id: 'streamable',
    name: 'Streamable',
    mark: 'play',
    shape: 'video',
    hosts: ['streamable.com'],
    frames: [
      ['^/e/(\\w+)$', 'https://streamable.com/e/$1'],
      ['^/(\\w+)$', 'https://streamable.com/e/$1'],
    ],
  },
  {
    id: 'mixcloud',
    name: 'Mixcloud',
    mark: 'play',
    shape: 120,
    hosts: ['mixcloud.com'],
    frames: [['^/[\\w-]+/[\\w-]+/?$', 'https://www.mixcloud.com/widget/iframe/?feed=$url']],
  },
  {
    id: 'codesandbox',
    name: 'CodeSandbox',
    mark: 'open',
    shape: 500,
    hosts: ['codesandbox.io'],
    frames: [
      ['^/s/([\\w-]+)', 'https://codesandbox.io/embed/$1'],
      ['^/p/sandbox/([\\w-]+)', 'https://codesandbox.io/embed/$1'],
      ['^/embed/([\\w-]+)', 'https://codesandbox.io/embed/$1'],
    ],
  },
  {
    id: 'stackblitz',
    name: 'StackBlitz',
    mark: 'open',
    shape: 500,
    hosts: ['stackblitz.com'],
    frames: [['^/edit/([\\w.-]+)', 'https://stackblitz.com/edit/$1?embed=1']],
  },
  {
    id: 'replit',
    name: 'Replit',
    mark: 'open',
    shape: 500,
    hosts: ['repl.it', 'replit.com'],
    frames: [['^/@([\\w-]+)/([\\w.-]+)', 'https://replit.com/@$1/$2?embed=true']],
  },
  {
    id: 'observable',
    name: 'Observable',
    mark: 'open',
    shape: 500,
    hosts: ['observablehq.com'],
    frames: [
      ['^/@([\\w-]+)/([\\w-]+)', 'https://observablehq.com/embed/@$1/$2'],
      ['^/d/(\\w+)', 'https://observablehq.com/embed/d/$1'],
    ],
  },
  {
    id: 'jsfiddle',
    name: 'JSFiddle',
    mark: 'open',
    shape: 400,
    hosts: ['jsfiddle.net'],
    frames: [['^/([\\w-]+)/([\\w-]+)/?$', 'https://jsfiddle.net/$1/$2/embedded/']],
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    mark: 'play',
    shape: 175,
    hosts: ['music.apple.com'],
    frames: [
      [
        '^/[\\w-]+/(?:album|song|playlist|artist|music-video)/',
        'https://embed.music.apple.com$path',
      ],
    ],
  },
  {
    id: 'apple-podcasts',
    name: 'Apple Podcasts',
    mark: 'play',
    shape: 175,
    hosts: ['podcasts.apple.com'],
    frames: [['^/[\\w-]+/podcast/', 'https://embed.podcasts.apple.com$path']],
  },
  {
    id: 'deezer',
    name: 'Deezer',
    mark: 'play',
    shape: 300,
    hosts: ['deezer.com'],
    frames: [
      [
        '^/(?:[\\w-]+/)?(album|playlist|track|show|episode)/(\\d+)',
        'https://widget.deezer.com/widget/dark/$1/$2',
      ],
    ],
  },
  {
    id: 'desmos',
    name: 'Desmos',
    mark: 'open',
    shape: 'video',
    hosts: ['desmos.com'],
    frames: [
      ['^/calculator/(\\w+)', 'https://www.desmos.com/calculator/$1?embed'],
      ['^/geometry/(\\w+)', 'https://www.desmos.com/geometry/$1?embed'],
    ],
  },
  {
    id: 'geogebra',
    name: 'GeoGebra',
    mark: 'open',
    shape: 'video',
    hosts: ['geogebra.org'],
    frames: [
      ['^/m/(\\w+)', 'https://www.geogebra.org/material/iframe/id/$1'],
      ['^/material/iframe/id/(\\w+)', 'https://www.geogebra.org/material/iframe/id/$1'],
    ],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    mark: 'open',
    shape: 700,
    hosts: ['calendly.com'],
    frames: [['^/[\\w-]+/[\\w-]+', 'https://calendly.com$path']],
  },
  {
    id: 'canva',
    name: 'Canva',
    mark: 'open',
    shape: 'video',
    hosts: ['canva.com'],
    frames: [
      ['^/design/([\\w-]+)/([\\w-]+)/view', 'https://www.canva.com/design/$1/$2/view?embed'],
    ],
  },
  {
    id: 'whimsical',
    name: 'Whimsical',
    mark: 'open',
    shape: 'video',
    hosts: ['whimsical.com'],
    frames: [['^/([\\w-]+-\\w{12,})$', 'https://whimsical.com/embed/$1']],
  },
  {
    id: 'flourish',
    name: 'Flourish',
    mark: 'open',
    shape: 'video',
    hosts: ['public.flourish.studio'],
    frames: [
      ['^/visualisation/(\\d+)', 'https://flo.uri.sh/visualisation/$1/embed'],
      ['^/story/(\\d+)', 'https://flo.uri.sh/story/$1/embed'],
    ],
  },
  {
    id: 'datawrapper',
    name: 'Datawrapper',
    mark: 'open',
    shape: 500,
    hosts: ['datawrapper.dwcdn.net'],
    frames: [['^/(\\w+)/(\\d+)', 'https://datawrapper.dwcdn.net/$1/$2/']],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    mark: 'open',
    shape: 600,
    hosts: ['pinterest.com'],
    frames: [['^/pin/(\\d+)', 'https://assets.pinterest.com/ext/embed.html?id=$1']],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    mark: 'open',
    shape: 700,
    hosts: ['instagr.am', 'instagram.com'],
    frames: [
      ['^/p/([\\w-]+)', 'https://www.instagram.com/p/$1/embed'],
      ['^/reel/([\\w-]+)', 'https://www.instagram.com/reel/$1/embed'],
      ['^/[\\w.]+/p/([\\w-]+)', 'https://www.instagram.com/p/$1/embed'],
    ],
  },
  {
    id: 'bluesky',
    name: 'Bluesky',
    mark: 'open',
    shape: 400,
    hosts: ['bsky.app'],
    frames: [
      [
        '^/profile/([\\w.:-]+)/post/(\\w+)',
        'https://embed.bsky.app/embed/$1/app.bsky.feed.post/$2',
      ],
    ],
  },
  {
    id: 'acast',
    name: 'Acast',
    mark: 'play',
    shape: 175,
    hosts: ['play.acast.com'],
    frames: [['^/s/([\\w-]+)/([\\w-]+)', 'https://embed.acast.com/$1/$2']],
  },
  {
    id: 'arcgis',
    name: 'ArcGIS StoryMaps',
    mark: 'open',
    shape: 'video',
    hosts: ['storymaps.arcgis.com'],
    frames: [['^/stories/(\\w+)', 'https://storymaps.arcgis.com/stories/$1']],
  },
  {
    id: 'padlet',
    name: 'Padlet',
    mark: 'open',
    shape: 600,
    hosts: ['padlet.com'],
    frames: [['^/[\\w-]+/([\\w-]+)$', 'https://padlet.com/embed/$1']],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    mark: 'open',
    shape: 600,
    hosts: ['airtable.com'],
    frames: [
      ['^/app\\w+/(shr\\w+)', 'https://airtable.com/embed/$1'],
      ['^/embed/(shr\\w+)', 'https://airtable.com/embed/$1'],
      ['^/(shr\\w+)', 'https://airtable.com/embed/$1'],
    ],
  },
  {
    id: 'imgur',
    name: 'Imgur',
    mark: 'open',
    shape: 600,
    hosts: ['imgur.com'],
    frames: [
      ['^/a/(\\w+)', 'https://imgur.com/a/$1/embed'],
      ['^/gallery/(\\w+)', 'https://imgur.com/a/$1/embed'],
    ],
  },
  {
    id: 'asciinema',
    name: 'asciinema',
    mark: 'play',
    shape: 400,
    hosts: ['asciinema.org'],
    frames: [['^/a/(\\w+)', 'https://asciinema.org/a/$1/iframe']],
  },
  {
    id: 'coub',
    name: 'Coub',
    mark: 'play',
    shape: 'video',
    hosts: ['coub.com'],
    frames: [
      ['^/view/(\\w+)', 'https://coub.com/embed/$1'],
      ['^/embed/(\\w+)', 'https://coub.com/embed/$1'],
    ],
  },
  {
    id: 'scribd',
    name: 'Scribd',
    mark: 'open',
    shape: 600,
    hosts: ['scribd.com'],
    frames: [['^/doc(?:ument)?/(\\d+)', 'https://www.scribd.com/embeds/$1/content']],
  },
]
